### PR TITLE
docker for macOS

### LINKED ISSUE #7: docker for macOS
To monitor stats when running the docker test net on macOS, we need a workaround.  I can work on this when I have more time.

Possible workaround - https://github.com/wojas/docker-mac-network

### PR DESCRIPTION
**Pull request by calvinchengx**
`watch.sh` in docker. Works as expected.

Fixes #7

### CODE REVIEW

**Comment by arrivets** [comment]
great stuff, thanks for updating the makefiles as well!

So when I run the demo and do a `docker attach watcher`, I see the following output
 
Every` 1s:                                                                                                                                                                                                                                                                                                  [0/1610]
for i in $(seq 1 4);
do
    curl -s -m 1 http://172.77.5.$i:80/Stats | \
        tr -d "{}\"" | \
        awk -F "," '{gsub (/[,]/," "); print;}'
done;
                                                                                                                            2017-12-04 08:39:13

consensus_events:91 consensus_transactions:40 events_per_second:0.00 id:1 last_consensus_round:9 num_peers:3 round_events:12 rounds_per_second:0.00 state:Babbling sync_rate:1.00 transaction_pool:0 undetermined_events:20
consensus_events:91 consensus_transactions:40 events_per_second:0.00 id:2 last_consensus_round:9 num_peers:3 round_events:12 rounds_per_second:0.00 state:Babbling sync_rate:1.00 transaction_pool:0 undetermined_events:21
consensus_events:91 consensus_transactions:40 events_per_second:0.00 id:0 last_consensus_round:9 num_peers:3 round_events:12 rounds_per_second:0.00 state:Babbling sync_rate:1.00 transaction_pool:0 undetermined_events:17
consensus_events:91 consensus_transactions:40 events_per_second:0.00 id:3 last_consensus_round:9 num_peers:3 round_events:12 rounds_per_second:0.00 state:Babbling sync_rate:1.00 transaction_pool:0 undetermined_events:20


Also I have to restart the container because it exits with an error code when running the demo on the first `make` call.

I m going to look into it but this is awesome

**Comment by arrivets** [comment]
ok forget what I said about the watcher exiting with an error code..
I hadnt seen that the container wasnt run in the background.. so I was killing it myself with ctl-C.

There remains that 

Every` 1s: [0/1610]
for i in $(seq 1 4);
do
curl -s -m 1 http://172.77.5.$i:80/Stats | 
tr -d "{}"" | 
awk -F "," '{gsub (/[,]/," "); print;}'
done;
2017-12-04 08:39:13

message in the output

**Comment by calvinchengx** [comment]
Cool.

Btw, drew this up on Sketch. Based on your answers to my earlier questions seeking clarification.

Will be using it in a babble/swirds demo tomorrow. Feel free to use it too.

---
www.calvinx.com

**Comment by calvinchengx** [comment]
[
hashgraph_babble_swirlds
](url)

**Comment by arrivets** [comment]
ah very nice!

**Pull request merged**
